first_name = input("Hey, what's your first name? : ")
last_name = input("And your last name? : ")
last_name = last_name.strip()
first_name = first_name.strip()
print(f"Well, pleased to meet you, {first_name} {last_name}.")